### ISSUE TITLE
Correlation matrix

### ISSUE THREAD

**Issue by gcescobar13** [berkeley-stat159/project-kappa#94]
Hi @matthew-brett ,

@changzheng1993 and I are having determining which of these will produce the right corr (7x7) matrix.

def difference_corr(beta, category):
    """ This functions return the correlation matrix of the two categories
    Parameters
    ----------
    beta:4D dimensions
        brain activation

```
category:
    choose a category to fix it.

return
------
correlation: 2D 
    correlation matrix
"""

difference = []

for i in np.concatenate((range(category-1), range(category ,8))):
    difference.append((beta[...,i]-beta[...,category-1]).reshape([-1]))

difference = np.array(difference)
correlation = np.zeros((7,7))
for j in range(7):
    for k in range(7):
        correlation[j,k] = np.corrcoef(difference[j],difference[k])[1,0]
return correlation
```

Or,

def diff_corr(betas, condition):
    differences = []
    betas_2d = betas.reshape((betas.shape[-1],-1))

```
for i in np.arange(8)[np.arange(8)!=condition-1]:
    differences.append(betas_2d[i,:] - betas_2d[condition-1,:])

return np.corrcoef(differences)
```

They both spit out the a 7x7 matrix but we're getting significantly different correlation outputs.

**Comment by matthew-brett** [comment]
You can debug this by doing a couple of correlations by hand - I mean, getting the beta vector for houses, the beta vector for faces, then subtracting the beta vector for scrambled and doing the correlation.

I think you'll find that the betas are different in the first function than in the second, hence the different correlations.   I worry about your reshape command in the second function.

**Comment by gcescobar13** [comment]
![scannable document on dec 11 2015 8_49_24 pm 1](https://cloud.githubusercontent.com/assets/14046131/11760261/d2f9d118-a049-11e5-9cfc-dd8e61ec5872.png)

the reshape is to get the (P x Voxel) on the right side. I might have misinterpreted your image. I'll debug now. thank you @matthew-brett

**Comment by matthew-brett** [comment]
Yes, you'll get the right shape, but filled with the wrong elements.  Remember that numpy.reshape will do this internally:
- flatten the input array to 1D, taking elements over the last dimension first;
- fill up the output array from the flat input, filling the last dimension first.

So, with your reshape, it will fill up the voxel-length rows with lots of time-courses.   To make sure the elements go in the right order, you'll have to reshape into V by T and then transpose.

Also - I still think you should used the mask instead of taking the whole 4D volume...
